package com.example.galaxyguardian.data.service.export

import android.content.Context
import android.net.Uri
import com.example.galaxyguardian.data.model.BotProject
import com.example.galaxyguardian.data.model.TargetLanguage
import com.example.galaxyguardian.data.service.llm.MultiFileProjectParser
import java.io.BufferedOutputStream
import java.util.zip.ZipEntry
import java.util.zip.ZipOutputStream

object ProjectExporter {

    fun exportProjectZip(context: Context, bot: BotProject, destinationUri: Uri): Boolean {
        return try {
            val parsedFiles = MultiFileProjectParser.parse(
                rawCode = bot.formattedCode.ifBlank { bot.generatedCode },
                defaultFileName = if (bot.toTargetLanguage() == TargetLanguage.KOTLIN_ANDROID) "MainActivity.kt" else "main.py"
            )

            context.contentResolver.openOutputStream(destinationUri)?.use { outputStream ->
                ZipOutputStream(BufferedOutputStream(outputStream)).use { zipOut ->
                    for (file in parsedFiles) {
                        val entry = ZipEntry(file.path)
                        zipOut.putNextEntry(entry)
                        zipOut.write(file.content.toByteArray(Charsets.UTF_8))
                        zipOut.closeEntry()
                    }

                    // Always attach a generated README.md
                    val readmeContent = generateProjectReadme(bot)
                    val readmeEntry = ZipEntry("README.md")
                    zipOut.putNextEntry(readmeEntry)
                    zipOut.write(readmeContent.toByteArray(Charsets.UTF_8))
                    zipOut.closeEntry()

                    // For Python projects attach Dockerfile and requirements.txt
                    if (bot.toTargetLanguage() == TargetLanguage.PYTHON) {
                        val reqEntry = ZipEntry("requirements.txt")
                        zipOut.putNextEntry(reqEntry)
                        zipOut.write("requests>=2.31.0\naiohttp>=3.9.0\npython-dotenv>=1.0.0\n".toByteArray(Charsets.UTF_8))
                        zipOut.closeEntry()

                        val dockerEntry = ZipEntry("Dockerfile")
                        zipOut.putNextEntry(dockerEntry)
                        val dockerfile = """
                            FROM python:3.11-slim
                            WORKDIR /app
                            COPY requirements.txt .
                            RUN pip install --no-cache-dir -r requirements.txt
                            COPY . .
                            CMD ["python", "main.py"]
                        """.trimIndent()
                        zipOut.write(dockerfile.toByteArray(Charsets.UTF_8))
                        zipOut.closeEntry()
                    }
                }
            }
            true
        } catch (e: Exception) {
            android.util.Log.e("ProjectExporter", "Failed to export ZIP", e)
            false
        }
    }

    private fun generateProjectReadme(bot: BotProject): String {
        return """
# ${bot.title}

Generated by **Galaxy Guardian AI Workbench**

## Project Overview
- **Prompt:** ${bot.prompt}
- **Language:** ${bot.targetLanguage}
- **Provider:** ${bot.providerType} (${bot.modelName})
- **Security Score:** ${bot.analysis.securityScore}/100

## Security Summary
${bot.analysis.securitySummaryText}

## Build & Usage Instructions
- **Kotlin/Android:** Import into Android Studio Ladybug (2024.2.1+) with JDK 21 and Android SDK 36.
- **Python:** Run `pip install -r requirements.txt` then `python main.py` or `docker build -t app .`.
""".trimIndent()
    }
}
